apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_ORG: org-fluidos
  INFLUXDB_URL: http://10.244.1.17:8086
  INFLUXDB_TOKEN: fluidos-edge-demo-token
  INFLUXDB_BUCKET: bucket-fluidos
