mqtt:
  server: tcp://0.0.0.0:1883
  username: ""
  password: ""
  certification: ""
configmap: /opt/kubeedge/deviceProfile.json
 
device-model-name: bluenrg
action-manager:
  actions:
    - name: EnvironmentalData
      perform-immediately: false
      device-property-name: temperature            #property-name defined in the device model

scheduler:
  schedules:
    - name: sensors
      interval: 3000
      occurrence-limit: 0            # if it is 0, then the event will execute infinitely
      actions:
        - EnvironmentalData          # Action name defined in the action-manager section
#watcher:
#  device-twin-attributes :
#    - device-property-name: io-data                     # the twin attribute name defined while creating device
#      actions:                         # list of action names, defined in the action-manager section, to be executed on the device
#        - IOConfigurationInitialize
#        - IODataInitialize
#        - IOConfiguration
#        - IOData

